#! /bin/bash

# Point IRAF-style CAL env vars into corresponding areas of CRDS cache.

export iref=${CRDS_PATH}/references/hst/iref/
export jref=${CRDS_PATH}/references/hst/jref/
export oref=${CRDS_PATH}/references/hst/oref/
export lref=${CRDS_PATH}/references/hst/lref/
export nref=${CRDS_PATH}/references/hst/nref/
export uref=${CRDS_PATH}/references/hst/uref/
export uref_linux=$uref

