#! /bin/bash

# This file defines required environment variables for the CRDS client and CAL s/w reference file location

# Connect to CRDS HST OPS server,  download personal dynamic cache

export CRDS_SERVER_URL=https://hst-crds.stsci.edu
export CRDS_PATH=${HOME}/crds_cache
export CRDS_READONLY_CACHE=0

source hstdputils-cal-env

python -m hstdputils.process none none $*

